### ISSUE TITLE
Inconsistent 

### ISSUE THREAD

**Issue by staudlol** [billdims/Fun-Commands#1]
I recommend staying consistent throughout with your methods and the utilities you use :)

**Comment by billdims** [comment]
ok listen to me little lad. if u ever say that my code is inconsistent then something very funny gonna happen. 

Greetings
bill :)

**Comment by pcranaway** [comment]
I am here to say that

**Comment by billdims** [comment]
Good morning Staud,

please do not be afraid and ask me if i care.

PS: get ratioed

Greetings
bill :)

**Comment by staudlol** [comment]
> Good morning Staud,
> 
> please do not be afraid and ask me if i care.
> 
> PS: get ratioed
> 
> Greetings bill :)

I hope Santa brings you many gifts for Christmas. God Bless.

**Comment by pcranaway** [comment]
I'm glad to say that this issue has been resolved privately.

**Comment by billdims** [comment]
Hey Staud, 

I hope your easter egg disappears in front of your eyes and never get your money 

Best wishes
bill :)

**Comment by staudlol** [comment]
> 

I do not like Easter eggs.

**Comment by billdims** [comment]
Good evening Staud

I wanted to say that it sounds like a user issue. I really don't care.

Greetings
bill :)
